#!/bin/sh

bspc config border_width         3
bspc config window_gap           12
bspc config top_padding          20

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc monitor -d I II III IV V VI VII VIII IX X

bspc rule -a Gimp state=floating follow=on
