#!/bin/sh

DIR=~/.dotfiles

symlinker() {
    echo "Symlinking dotfiles"
    for dot in $(ls dots) ; do
	if [ -z ~/.$dot ] || [ -d ~/.$dot ]; then
	    rm -rf ~/.$dot
	fi
	ln -sf $DIR/dots/$dot ~/.$dot
    done

    echo "You're all set!"
}

symlinker
exit $?
