#!/bin/sh

mkdir -p $HOME/doc
mkdir -p $HOME/down
mkdir -p $HOME/mus
mkdir -p $HOME/img
mkdir -p $HOME/vid
mkdir -p $HOME/mnt
mkdir -p $HOME/code

xdg-user-dirs-update --set DOCUMENTS $HOME/doc
xdg-user-dirs-update --set DOWNLOAD $HOME/down
xdg-user-dirs-update --set DESKTOP $HOME/
xdg-user-dirs-update --set MUSIC $HOME/mus
xdg-user-dirs-update --set PICTURES $HOME/img
xdg-user-dirs-update --set VIDEOS $HOME/vid
xdg-user-dirs-update --set PUBLICSHARE $HOME/
xdg-user-dirs-update --set TEMPLATES $HOME/

emptyCheck() {
    target = $1
    if find "$target" -mindepth 1 -print -quit | grep -q .; then
        echo there are files in $target
    else
        rm -rf $target
    fi
}

emptyCheck $HOME/Documents
emptyCheck $HOME/Downloads
emptyCheck $HOME/Music
emptyCheck $HOME/Pictures
emptyCheck $HOME/Videos
emptyCheck $HOME/Templates

